apiVersion: v1
kind: Service
metadata:
  name: {{ template "demoapp.fullname" . }}
  labels:
    app: {{ template "demoapp.name" . }}
    chart: {{ template "demoapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{.Values.service.port}}
      protocol: TCP
      name: {{ .Values.servicename }}
  selector:
    app: {{ template "demoapp.name" . }}
    release: {{ .Release.Name }}
